version: "3.8"

services:
  nodejs:
    build:
      context: .
    container_name: nodejs
    ports:
      - "8000:8000"
      - "9229:9229"
    command: npm run dev
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
